#ifndef TEA_GFX_COLOUR_H
#define TEA_GFX_COLOUR_H

#include <cstdint>

namespace tea {

class ColourRGB {
public:
    ColourRGB(double r, double g, double b, double a = 1.0);

    void set(double r, double g, double b, double a = 1.0);

    [[nodiscard]] double get_r() const;
    [[nodiscard]] double get_g() const;
    [[nodiscard]] double get_b() const;
    [[nodiscard]] double get_a() const;
    [[nodiscard]] uint32_t get_rgba_bytes() const;
    [[nodiscard]] ColourRGB get_inverted() const;
    [[nodiscard]] ColourRGB get_greyscale() const;

    static ColourRGB from_bytes(uint8_t r, uint8_t g, uint8_t b, uint8_t a = 255);
    static const ColourRGB
        ALICEBLUE,
        ANTIQUEWHITE,
        AQUA,
        AQUAMARINE,
        AZURE,
        BEIGE,
        BISQUE,
        BLACK,
        BLANCHEDALMOND,
        BLUE,
        BLUEVIOLET,
        BROWN,
        BURLYWOOD,
        CADETBLUE,
        CHARTREUSE,
        CHOCOLATE,
        CORAL,
        CORNFLOWERBLUE,
        CORNSILK,
        CRIMSON,
        CYAN,
        DARKBLUE,
        DARKCYAN,
        DARKGOLDENROD,
        DARKGRAY,
        DARKGREEN,
        DARKGREY,
        DARKKHAKI,
        DARKMAGENTA,
        DARKOLIVEGREEN,
        DARKORANGE,
        DARKORCHID,
        DARKRED,
        DARKSALMON,
        DARKSEAGREEN,
        DARKSLATEBLUE,
        DARKSLATEGRAY,
        DARKSLATEGREY,
        DARKTURQUOISE,
        DARKVIOLET,
        DEEPPINK,
        DEEPSKYBLUE,
        DIMGRAY,
        DIMGREY,
        DODGERBLUE,
        FIREBRICK,
        FLORALWHITE,
        FORESTGREEN,
        FUCHSIA,
        GAINSBORO,
        GHOSTWHITE,
        GOLD,
        GOLDENROD,
        GRAY,
        GREEN,
        GREENYELLOW,
        GREY,
        HONEYDEW,
        HOTPINK,
        INDIANRED,
        INDIGO,
        IVORY,
        KHAKI,
        LAVENDER,
        LAVENDERBLUSH,
        LAWNGREEN,
        LEMONCHIFFON,
        LIGHTBLUE,
        LIGHTCORAL,
        LIGHTCYAN,
        LIGHTGOLDENRODYELLOW,
        LIGHTGRAY,
        LIGHTGREEN,
        LIGHTGREY,
        LIGHTPINK,
        LIGHTSALMON,
        LIGHTSEAGREEN,
        LIGHTSKYBLUE,
        LIGHTSLATEGRAY,
        LIGHTSLATEGREY,
        LIGHTSTEELBLUE,
        LIGHTYELLOW,
        LIME,
        LIMEGREEN,
        LINEN,
        MAGENTA,
        MAROON,
        MEDIUMAQUAMARINE,
        MEDIUMBLUE,
        MEDIUMORCHID,
        MEDIUMPURPLE,
        MEDIUMSEAGREEN,
        MEDIUMSLATEBLUE,
        MEDIUMSPRINGGREEN,
        MEDIUMTURQUOISE,
        MEDIUMVIOLETRED,
        MIDNIGHTBLUE,
        MINTCREAM,
        MISTYROSE,
        MOCCASIN,
        NAVAJOWHITE,
        NAVY,
        OLDLACE,
        OLIVE,
        OLIVEDRAB,
        ORANGE,
        ORANGERED,
        ORCHID,
        PALEGOLDENROD,
        PALEGREEN,
        PALETURQUOISE,
        PALEVIOLETRED,
        PAPAYAWHIP,
        PEACHPUFF,
        PERU,
        PINK,
        PLUM,
        POWDERBLUE,
        PURPLE,
        RED,
        ROSYBROWN,
        ROYALBLUE,
        SADDLEBROWN,
        SALMON,
        SANDYBROWN,
        SEAGREEN,
        SEASHELL,
        SIENNA,
        SILVER,
        SKYBLUE,
        SLATEBLUE,
        SLATEGRAY,
        SLATEGREY,
        SNOW,
        SPRINGGREEN,
        STEELBLUE,
        TAN,
        TEAL,
        THISTLE,
        TOMATO,
        TURQUOISE,
        VIOLET,
        WHEAT,
        WHITE,
        WHITESMOKE,
        YELLOW,
        YELLOWGREEN;

protected:
    double r, g, b, a;
};

}

#endif // TEA_GFX_COLOUR_H